unstable_features = true

edition = "2024"

blank_lines_upper_bound = 1
color = "Always"
doc_comment_code_block_width = 80
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = true
# float_literal_trailing_zero = "IfNoPostfix"
force_explicit_abi = true
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
max_width = 80
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
