# https://github.com/jonhoo/rust-ci-conf/tree/main/.github/workflows

name: CI

on:
    push:
        branches: [main]
        tags: ['v*']
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

env:
    RUSTFLAGS: '-D warnings'
    RUSTDOCFLAGS: '-D warnings'
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: nightly
                  components: rustfmt
            - uses: Swatinem/rust-cache@v2
            - uses: taiki-e/install-action@just
            # not used, but required in justfile
            - uses: taiki-e/install-action@cargo-hack
            - run: just fmt check

    clippy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  components: clippy
            - uses: Swatinem/rust-cache@v2
            - uses: taiki-e/install-action@just
            - uses: taiki-e/install-action@cargo-hack
            - run: just clippy

    test:
        strategy:
            fail-fast: false
            matrix:
                toolchain: ['stable', 'beta', 'nightly']
                os: ['ubuntu', 'macOS', 'windows']
        runs-on: ${{ matrix.os }}-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
            - uses: taiki-e/install-action@just
            - uses: taiki-e/install-action@cargo-hack
            - run: just test ${{ matrix.toolchain }}

    doc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: nightly
                  components: rust-docs
            - uses: Swatinem/rust-cache@v2
            - uses: taiki-e/install-action@just
            - uses: taiki-e/install-action@cargo-hack
            - run: just doc "" private

    msrv:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@nightly
            - uses: Swatinem/rust-cache@v2
            - uses: taiki-e/install-action@just
            - uses: taiki-e/install-action@cargo-hack
            - run: just msrv
